version: '3.3'

services:
  nutricraft-app:
    container_name: nutricraft-app
    build: nutricraft-app
    ports:
      - 3001:3001
    depends_on:
      - postgres-app
    environment:
      DB_HOST: ${DB_HOST_APP}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT_APP}
    volumes:
      - ./nutricraft-app:/app/nutricraft-app

  nutricraft-express:
    container_name: nutricraft-express
    build: nutricraft-express
    depends_on:
      - postgres-express
      - cache
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST_EXPRESS}:5432/${DB_NAME}?schema=public
      DATABASE_URL_REDIS: redis://:${DB_PASSWORD_REDIS}@redis:6379
      JWT_KEY: ${JWT_KEY}
      REFRESH_KEY : ${REFRESH_KEY}
      SOAP_KEY: ${SOAP_KEY_REST}
      SOAP_URL_SUBSCRIBE: ${SOAP_URL_SUBSCRIBE}
      SOAP_URL_LEVEL: ${SOAP_URL_CREATOR_LEVEL}
      SOAP_URL_COIN: ${SOAP_URL_COIN}
    volumes:
      - ./nutricraft-express:/app/nutricraft-express
      - /app/nutricraft-express/node_modules

  nutricraft-soap:
    container_name: nutricraft-soap
    build: ./nutricraft-soap
    ports:
      - 8081:8081
    depends_on:
      - mysql-soap
    environment:
      DATABASE_URL: jdbc:mysql://${DB_HOST_SOAP}:3306/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SOAP_KEY_REST: ${SOAP_KEY_REST}
      SOAP_KEY_APP: ${SOAP_KEY_APP}

  nutricraft-spa:
    container_name: nutricraft-spa
    build: nutricraft-spa
    ports:
      - 3000:3000
    volumes:
      - ./nutricraft-spa:/app/nutricraft-spa
      - /app/nutricraft-spa/node_modules


  postgres-app:
    image: postgres:latest
    container_name: postgres-app
    restart: always
    ports:
      - ${DB_PORT_APP}:${DB_PORT_APP}
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data1:/var/lib/postgresql
    hostname: ${DB_HOST_APP}

  postgres-express:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT_EXPRESS}:5432
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data2:/var/lib/postgresql
    hostname: ${DB_HOST_EXPRESS}

  mysql-soap:
    image: mysql:latest
    container_name: mysql-soap
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    hostname: ${DB_HOST_SOAP}
    volumes:
    - ./nutricraft-soap/db/db.sql:/docker-entrypoint-initdb.d/db.sql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    hostname: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_PASSWORD_REDIS}
    volumes:
      - cache:/data


volumes:
  db-data1:
  db-data2:
  cache:
    driver: local