version: '3.3'

services:
  nutricraft-app:
    container_name: nutrilife-app
    build: nutricraft-app
    ports:
      - 3001:3001
    depends_on:
      - postgres-app
    environment:
      DB_HOST: ${DB_HOST_APP}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT_APP}
    volumes:
      - ./nutricraft-app:/app/nutricraft-app

  nutricraft-express:
    container_name: nutricraft-express
    build: nutricraft-express
    depends_on:
      - postgres-express
      - cache
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL_EXPRESS}
      JWT_KEY: ${JWT_KEY}
    volumes:
      - ./nutricraft-express:/app/nutricraft-express

  nutricraft-soap:
    container_name: nutricraft-soap
    build: ./nutricraft-soap
    ports:
      - 8081:8081
    depends_on:
      - mysql-soap
    environment:
      DATABASE_URL: ${DATABASE_URL_SOAP}
    volumes:
      - .:/app/nutricraft-soap

  nutricraft-spa:
    container_name: nutricraft-spa
    build: nutricraft-spa
    ports:
      - 3000:3000
    volumes:
      - ./nutricraft-spa:/app/nutricraft-spa
      - /app/nutricraft-spa/node_modules


  postgres-app:
    image: postgres:latest
    container_name: postgres-app
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data1:/var/lib/postgresql

  postgres-express:
    image: postgres:latest
    container_name: postgres-express
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data2:/var/lib/postgresql

  mysql-soap:
    image: mysql:latest
    container_name: mysql-soap
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_DB: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data



volumes:
  db-data1:
  db-data2:
  cache:
    driver: local